name: CI Build Linux

on: 
  push:
    branches: ["main"]
    tags:
      - 'v[0-9]+.[0-9]+'
  pull_request:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      file_type:
        description: 'File type to upload (hex or elf)'
        required: true
        default: 'hex'
        type: choice
        options:
          - hex
          - elf

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Build CI
        shell: bash
        run: |
          make arm_sdk_install
          make AORC_K_A_F421
          # MENIRU PABRIKAN: Menyalin file dan memberi nama format asli AM32 di folder terluar
          find . -name "*AORC_K_A_F421*.hex" -exec cp {} ./AM32_AORC_K_A_F421_2.20.hex \;

      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: AM32-AORC-hex-only
          path: AM32_AORC_K_A_F421_2.20.hex
          retention-days: 60
